In [3]:
x = (32, 10)
y = (10,)

print(len(x))

2


In [6]:
print(range(x[1]))

range(0, 10)


In [10]:
def naive_add_matrix_and_vector(x,y):
    assert len(x.shape) == 2
    assert len(y.shape) ==1
    assert x.shape[1] == y.shape[0]
    
    x = x.copy()
    for i in range(x.shape[0]):   #range(x[1]) = range(0, 10)
        for j in range(x.shape[1]):
            x[i, j] += y[j]
    return x

In [12]:
import numpy as np

x = np.random.random((32, 10))
y = np.random.random((10))

In [13]:
naive_add_matrix_and_vector(x,y)

array([[1.24925555, 1.26532867, 0.98915885, 0.94774684, 0.3290168 ,
        1.35513961, 0.40734325, 1.26148417, 0.76003541, 0.67110303],
       [1.77032024, 0.62344043, 0.47601382, 1.04997702, 0.42925764,
        1.40119335, 0.46431116, 1.23415094, 1.40313015, 0.34054143],
       [1.14199431, 0.65134735, 0.52406055, 0.87812445, 0.28546384,
        1.37981063, 0.94198763, 0.65146484, 0.88162615, 0.91696915],
       [0.81916279, 1.56273995, 1.01384146, 1.31327483, 0.27678986,
        1.73847421, 1.13608197, 1.31115199, 1.08557586, 0.46686393],
       [0.91209217, 1.21360119, 0.21951479, 1.2492084 , 0.7820973 ,
        0.96480469, 0.40240312, 1.10459206, 0.81472883, 0.31845692],
       [1.60992184, 1.29268672, 1.06717242, 1.0565702 , 0.94262272,
        1.32838584, 0.33349739, 1.1715478 , 1.48386576, 0.31683849],
       [1.2338341 , 1.06754466, 0.61132384, 1.43919572, 0.4840543 ,
        1.48479697, 1.02233357, 0.8497611 , 1.14652234, 0.53908589],
       [1.31232393, 0.70296411, 0.4659770

In [14]:
print(y.shape)

(10,)


In [15]:
z = np.maximum(x,y)

In [16]:
print(z.shape)

(32, 10)


In [17]:
print(y.shape[0])

10


In [18]:
print(x.shape[1])

10


In [19]:
print(len(x.shape))

2


In [22]:
x = np.random.random((6,4,5))
print(x)

[[[0.83263147 0.82128738 0.00388658 0.30658671 0.54470565]
  [0.45739167 0.14139575 0.70498514 0.60620052 0.7155321 ]
  [0.96112482 0.27533298 0.28540818 0.32055223 0.84135301]
  [0.66839225 0.61119879 0.96377898 0.43660768 0.12480602]]

 [[0.0596863  0.26947889 0.87267817 0.90689755 0.64223147]
  [0.03488885 0.57295463 0.5724387  0.02027675 0.3040414 ]
  [0.51812786 0.10493499 0.48308547 0.6932368  0.87214784]
  [0.28606134 0.78465116 0.86395171 0.58556832 0.05095862]]

 [[0.89891038 0.38742521 0.10451244 0.98540703 0.52423278]
  [0.27200033 0.02386687 0.76741519 0.22543588 0.4854954 ]
  [0.76394721 0.95012899 0.30733388 0.03485276 0.82797048]
  [0.30152488 0.72249    0.33200073 0.69901429 0.73447358]]

 [[0.73847498 0.24189359 0.55574925 0.10183893 0.77890798]
  [0.7892799  0.67064881 0.9242538  0.94613042 0.9453883 ]
  [0.5482655  0.17576003 0.14032616 0.52832133 0.61411532]
  [0.72321212 0.30729496 0.87994955 0.22204842 0.46525016]]

 [[0.28032549 0.9165059  0.31282623 0.40765671 0

In [23]:
print(len(x.shape))

3
